Rename items for personalization

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -151,8 +151,8 @@ then
   fi
 fi
 
-jldeenMods () {
-  info "starting jldeen mods"
+installMods () {
+  info "starting aaroncoville's mods"
   #backup old bin, if exists
   if [ -d $HOME/bin ]; then
     info "current $HOME/bin folder, checking for existing symlink"
@@ -167,7 +167,7 @@ jldeenMods () {
   fi
 }
 
-jd_Symlinks () {
+symlinks () {
   # symlink .dotfiles bin to ~
   ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder created"
 
@@ -195,12 +195,12 @@ jd_Symlinks () {
     fi
 }
 
-jdcolors () {
+colors () {
   # colorls setup
   sudo gem install colorls && success 'ls colors have been configured'
 }
 
-jdcrontab () {
+crontab () {
   #crontab additions
   add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     if [[ $? -eq 0 ]]
@@ -235,9 +235,9 @@ jdcrontab () {
   success "speedtest-cli bandwidth.json created"
 }
 
-jditermConfig () {
+itermConfig () {
   # iterm2 config
-  read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n " -n 1 -r
+  read -p "Do you currently use iTerm2 and would you like to set aaroncoville's custom colors? y/n " -n 1 -r
   echo ''
   if [[ $REPLY =~ ^[Yy]$ ]]
   then
@@ -247,22 +247,22 @@ jditermConfig () {
     defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
       if [[ $? -eq 0 ]]
       then
-          success "successfully configured iTerm2 to use jldeen's custom colors..."
+          success "successfully configured iTerm2 to use aaroncoville's custom colors..."
       else
-          fail "failed to apply jldeen's custom colors..." >&2
+          fail "failed to apply aaroncoville's custom colors..." >&2
   fi
   else 
-      info "You chose not to use iTerm2 or jldeen's custom colors."
+      info "You chose not to use iTerm2 or aaroncoville's custom colors."
   fi
 }
 
-jdFontSetup () {
+fontSetup () {
   # install Source Code Pro nerd font
   sudo cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
   success "Source Code Pro font copied successfully!"
 }
 
-jdconfigFix () {
+configFix () {
   # .config permissions fix
   if [ ! -d "$HOME/.config" ]; then
     info "$HOME/.config doesn't exist, nothing to fix"
@@ -272,12 +272,12 @@ jdconfigFix () {
   fi
 }
 
-jldeenMods
-jd_Symlinks
-jdcolors
+installMods
+symlinks
+colors
 #jdcrontab
-jditermConfig
-jdFontSetup
-jdconfigFix
+itermConfig
+fontSetup
+configFix
 
 success 'Badass macOS terminal installed!'
